name: Monitor de celulares

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  monitorar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: python teste_tudocelular.py
          pip install -r requirements.txt

      - name: Executar TudoCelular
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: 
          python teste_tudocelular.py
